version: "3.9"

services:
  # Redis'i tutuyoruz çünkü RDS sadece SQL veritabanıdır.
  redis:
    image: redis:7-alpine
    container_name: smartprogress-redis
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    networks:
      - smartprogress-network

  backend:
    build: ./backend
    container_name: smartprogress-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL} # GitHub Secrets'tan gelecek
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartprogress-network

  frontend:
    build: ./frontend
    container_name: smartprogress-frontend
    restart: unless-stopped
    ports:
      - "80:8081"
    environment:
      # ÖNEMLİ: 0.0.0.0 hatasını bu değişkenler ve host ayarı çözer
      EXPO_DEV_CLIENT_NETWORK_OPTION: lan
      NODE_ENV: production
      API_URL: http://3.71.189.248:3000 # Kendi sunucu IP'ni buraya yaz
    # Dockerfile'daki CMD'yi burada ezerek hata veren parametreyi düzeltiyoruz
    command: [ "npx", "expo", "start", "--web", "--host", "lan", "--non-interactive" ]
    networks:
      - smartprogress-network

networks:
  smartprogress-network:
    driver: bridge
