version: "3.9"

services:
  # Redis'i tutuyoruz çünkü RDS sadece SQL veritabanıdır.
  redis:
    image: redis:7-alpine
    container_name: smartprogress-redis
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    networks:
      - smartprogress-network

  backend:
    build: ./backend
    container_name: smartprogress-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL} # GitHub Secrets'tan gelecek
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartprogress-network

  frontend:
    build: ./frontend
    container_name: smartprogress-frontend
    restart: unless-stopped
    ports:
      - "80:8081" # Dışarıdan 80 (HTTP) gelen isteği Expo Web'e yönlendirir
    environment:
      API_URL: http://${AWS_HOST}:3000
    networks:
      - smartprogress-network

networks:
  smartprogress-network:
    driver: bridge
